services:
  tiktok_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${MY_IMAGE:-tiktok_api:latest}
    env_file:
      - .env
    environment:
      - SENTRY_ENVIRONMENT=production
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./download:/app/download
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:80"
    platform: linux/amd64
    networks:
      - tiktok_api_network

networks:
  tiktok_api_network:
    driver: bridge
